// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: chirps.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createChirp = `-- name: CreateChirp :one
INSERT INTO
    chirps (body, user_id, created_at, updated_at)
VALUES
    ($1, $2, $3, $4)
RETURNING
    id, user_id, body, created_at, updated_at
`

type CreateChirpParams struct {
	Body      sql.NullString
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
}

func (q *Queries) CreateChirp(ctx context.Context, arg CreateChirpParams) (Chirp, error) {
	row := q.db.QueryRowContext(ctx, createChirp,
		arg.Body,
		arg.UserID,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	var i Chirp
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Body,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChirp = `-- name: DeleteChirp :exec
DELETE FROM
    chirps
WHERE
    user_id = $1
`

func (q *Queries) DeleteChirp(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteChirp, userID)
	return err
}
