@host = localhost:8080


### Validate chirp

POST /api/validate_chirp HTTP/1.1
Host: {{host}}
Content-Type: "application/json"

{
  "body": "I hear Mastodon is better than Chirpy. sharbert I need to migrate"
}


### Get health check

GET /api/healthz HTTP/1.1
Host: {{host}}


### Create user

POST /api/users HTTP/1.1
Host: {{host}}
Content-Type: "application/json"

{
  "email": "user@example.com"
}


### Create chirp

POST /api/chirps HTTP/1.1
Host: {{host}}
Content-Type: "application/json"

{
  "body": "Hello, world!",
  "user_id": "05a0048c-7ef3-4ae9-886a-3e3dfc011777"
}


### Get chirps

GET /api/chirps HTTP/1.1
Host: {{host}}
Content-Type: "application/json"


### Get chirp

# @prompt chirp

GET /api/chirps/{{chirp}} HTTP/1.1
Host: {{host}}
Content-Type: "application/json"
