### 

@host = localhost:8080
@refreshToken = Bearer b379b50290898d961238116b3c970d9b49d2dfd46ca4634eeff5645e79c57dd9
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiI0MzIxOTI0Zi0yYzc0LTQwNjYtOTFjNS05MzRhODA0MmY3OGMiLCJleHAiOjE3NTgxMTc2ODEsImlhdCI6MTc1ODExNDA4MX0.lWXhyI5nWV_8tQv6mq-3UZ4LblTy9nSDT0zX2FAE1jM


### Login

POST /api/login HTTP/1.1
Host: {{host}}
Content-Type: "application/json"

{
  "email": "saul@bettercall.com",
  "password": "123457"
}


### Refresh Token

POST /api/refresh HTTP/1.1
Host: {{host}}
Content-Type: "application/json"
Authorization: {{refreshToken}}


### Revoke Token

POST /api/revoke HTTP/1.1
Host: {{host}}
Content-Type: "application/json"
Authorization: {{refreshToken}}


### Get health check

GET /api/healthz HTTP/1.1
Host: {{host}}


### Create user

POST /api/users HTTP/1.1
Host: {{host}}
Content-Type: "application/json"

{
  "email": "saul@bettercall.com",
  "password": "123456"
}


### Update user

PUT /api/users HTTP/1.1
Host: {{host}}
Content-Type: "application/json"
Authorization: {{token}}

{
  "email": "saul@bettercall.com",
  "password": "thepassword"
}


### Create chirp

POST /api/chirps HTTP/1.1
Host: {{host}}
Content-Type: "application/json"
Authorization: {{token}}

{
  "body": "Hello, world!"
}


### Get chirps

GET /api/chirps HTTP/1.1
Host: {{host}}
Content-Type: "application/json"


### Get chirp

# @prompt chirp

GET /api/chirps/{{chirp}} HTTP/1.1
Host: {{host}}
Content-Type: "application/json"
