### 

@host = localhost:8080
@refreshToken = Bearer 0604e365e0fabddde3ff3273e5283aedc16769b57d2273c3c6853eb973193bbd
@token = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjaGlycHkiLCJzdWIiOiJlNzViOTkwOS1lMTRiLTRjMzgtOWE4Zi1mZmViODFiODUwMDQiLCJleHAiOjE3NTkyMDYzOTcsImlhdCI6MTc1OTIwMjc5N30.zO7WX3fCoOeqAULnpZheZ_gKzNIbDYEko9TJus8zL8g


### Login

POST /api/login HTTP/1.1
Host: {{host}}
Content-Type: "application/json"

{
  "email": "saul@bettercall.com",
  "password": "123456"
}


### Refresh Token

POST /api/refresh HTTP/1.1
Host: {{host}}
Content-Type: "application/json"
Authorization: {{refreshToken}}


### Revoke Token

POST /api/revoke HTTP/1.1
Host: {{host}}
Content-Type: "application/json"
Authorization: {{refreshToken}}


### Get health check

GET /api/healthz HTTP/1.1
Host: {{host}}


### Create user

POST /api/users HTTP/1.1
Host: {{host}}
Content-Type: "application/json"

{
  "email": "saul@bettercall.com",
  "password": "123456"
}


### Update user

PUT /api/users HTTP/1.1
Host: {{host}}
Content-Type: "application/json"
Authorization: {{token}}

{
  "email": "saul@bettercall.com",
  "password": "thepassword"
}


### Create chirp

POST /api/chirps HTTP/1.1
Host: {{host}}
Content-Type: "application/json"
Authorization: {{token}}

{
  "body": "Hello, world!"
}


### Get chirps

GET /api/chirps?author_id HTTP/1.1
Host: {{host}}
Content-Type: "application/json"


### Get chirps by author

@authorID = 891f344b-0b01-4b5e-be93-646a20ffd5a1

GET /api/chirps?author_id={{authorID}} HTTP/1.1
Host: {{host}}
Content-Type: "application/json"


### Get chirp

# @prompt chirp

GET /api/chirps/{{chirp}} HTTP/1.1
Host: {{host}}
Content-Type: "application/json"


### Polka Webhook

POST /api/polka/webhooks HTTP/1.1
Host: {{host}}
Content-Type: "application/json"
Authorization: ApiKey f271c81ff7084ee5b99a5091b42d486e

{
  "data": {
    "user_id": "c22cc679-eb03-411b-91b3-ccbb7dfc1a27"
  },
  "event": "user.upgraded"
}
